# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\konda\envs\kub\lib\site-packages\pyqt5_tools\pogoda_prevac.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WeatherApp(object):
    def setupUi(self, WeatherApp):
        WeatherApp.setObjectName("WeatherApp")
        WeatherApp.resize(793, 413)
        WeatherApp.setMinimumSize(QtCore.QSize(350, 400))
        self.centralwidget = QtWidgets.QWidget(WeatherApp)
        self.centralwidget.setObjectName("centralwidget")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(110, 270, 161, 51))
        self.refreshButton.setObjectName("refreshButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(56, 30, 131, 20))
        self.label.setObjectName("label")
        self.dateRefresh = QtWidgets.QLineEdit(self.centralwidget)
        self.dateRefresh.setGeometry(QtCore.QRect(200, 30, 113, 20))
        self.dateRefresh.setObjectName("dateRefresh")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 70, 261, 170))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.weatherLine = QtWidgets.QLineEdit(self.frame)
        self.weatherLine.setObjectName("weatherLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.weatherLine)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.temperatureLine = QtWidgets.QLineEdit(self.frame)
        self.temperatureLine.setObjectName("temperatureLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.temperatureLine)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.tempFeelsLine = QtWidgets.QLineEdit(self.frame)
        self.tempFeelsLine.setObjectName("tempFeelsLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tempFeelsLine)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.pessureLine = QtWidgets.QLineEdit(self.frame)
        self.pessureLine.setObjectName("pessureLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pessureLine)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.windSpeedLine = QtWidgets.QLineEdit(self.frame)
        self.windSpeedLine.setObjectName("windSpeedLine")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.windSpeedLine)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.humidityLine = QtWidgets.QLineEdit(self.frame)
        self.humidityLine.setObjectName("humidityLine")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.humidityLine)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(60, 100, 160, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.wykresLabel = QtWidgets.QLabel(self.centralwidget)
        self.wykresLabel.setGeometry(QtCore.QRect(390, 80, 311, 241))
        self.wykresLabel.setText("")
        self.wykresLabel.setObjectName("wykresLabel")
        self.radioTemp = QtWidgets.QRadioButton(self.centralwidget)
        self.radioTemp.setGeometry(QtCore.QRect(360, 0, 101, 20))
        self.radioTemp.setChecked(True)
        self.radioTemp.setObjectName("radioTemp")
        self.radioPress = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPress.setGeometry(QtCore.QRect(470, 0, 81, 20))
        self.radioPress.setObjectName("radioPress")
        self.radioSpeed = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSpeed.setGeometry(QtCore.QRect(550, 0, 121, 20))
        self.radioSpeed.setObjectName("radioSpeed")
        self.radioHuminity = QtWidgets.QRadioButton(self.centralwidget)
        self.radioHuminity.setGeometry(QtCore.QRect(670, 0, 95, 20))
        self.radioHuminity.setObjectName("radioHuminity")
        self.zoomButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomButton.setGeometry(QtCore.QRect(470, 30, 161, 31))
        self.zoomButton.setCheckable(True)
        self.zoomButton.setChecked(False)
        self.zoomButton.setObjectName("zoomButton")
        WeatherApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WeatherApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuWy_wietl_historyczne_dane = QtWidgets.QMenu(self.menuMenu)
        self.menuWy_wietl_historyczne_dane.setObjectName("menuWy_wietl_historyczne_dane")
        self.menuWsp_rz_dne_2 = QtWidgets.QMenu(self.menuMenu)
        self.menuWsp_rz_dne_2.setObjectName("menuWsp_rz_dne_2")
        WeatherApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WeatherApp)
        self.statusbar.setObjectName("statusbar")
        WeatherApp.setStatusBar(self.statusbar)
        self.actionMinumum = QtWidgets.QAction(WeatherApp)
        self.actionMinumum.setObjectName("actionMinumum")
        self.actionMaksimum = QtWidgets.QAction(WeatherApp)
        self.actionMaksimum.setObjectName("actionMaksimum")
        self.actionSrednia = QtWidgets.QAction(WeatherApp)
        self.actionSrednia.setObjectName("actionSrednia")
        self.action35_88 = QtWidgets.QAction(WeatherApp)
        self.action35_88.setObjectName("action35_88")
        self.action36 = QtWidgets.QAction(WeatherApp)
        self.action36.setObjectName("action36")
        self.Xcoord = QtWidgets.QAction(WeatherApp)
        self.Xcoord.setObjectName("Xcoord")
        self.Ycoord = QtWidgets.QAction(WeatherApp)
        self.Ycoord.setObjectName("Ycoord")
        self.menuWy_wietl_historyczne_dane.addAction(self.actionMinumum)
        self.menuWy_wietl_historyczne_dane.addAction(self.actionMaksimum)
        self.menuWy_wietl_historyczne_dane.addAction(self.actionSrednia)
        self.menuWsp_rz_dne_2.addAction(self.Xcoord)
        self.menuWsp_rz_dne_2.addAction(self.Ycoord)
        self.menuMenu.addAction(self.menuWy_wietl_historyczne_dane.menuAction())
        self.menuMenu.addAction(self.menuWsp_rz_dne_2.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(WeatherApp)
        QtCore.QMetaObject.connectSlotsByName(WeatherApp)

    def retranslateUi(self, WeatherApp):
        _translate = QtCore.QCoreApplication.translate
        WeatherApp.setWindowTitle(_translate("WeatherApp", "MainWindow"))
        self.refreshButton.setText(_translate("WeatherApp", "ODŚWIEŻ"))
        self.label.setText(_translate("WeatherApp", "Ostatni raz odświeżono: "))
        self.dateRefresh.setText(_translate("WeatherApp", "1.1.2020, 21.37"))
        self.label_9.setText(_translate("WeatherApp", "Pogoda"))
        self.weatherLine.setText(_translate("WeatherApp", "Pochmurnie"))
        self.label_2.setText(_translate("WeatherApp", "Temperatura"))
        self.temperatureLine.setText(_translate("WeatherApp", "2 st. C."))
        self.label_8.setText(_translate("WeatherApp", "Temp. odczuwalna"))
        self.tempFeelsLine.setText(_translate("WeatherApp", "2 st. C."))
        self.label_3.setText(_translate("WeatherApp", "Ciśnienie"))
        self.pessureLine.setText(_translate("WeatherApp", "1013,25 hPa"))
        self.label_4.setText(_translate("WeatherApp", "Prędkość wiatru"))
        self.windSpeedLine.setText(_translate("WeatherApp", "8 m/s"))
        self.label_6.setText(_translate("WeatherApp", "Wilgotność powietrza"))
        self.humidityLine.setText(_translate("WeatherApp", "68%"))
        self.radioTemp.setText(_translate("WeatherApp", "Temperatura"))
        self.radioPress.setText(_translate("WeatherApp", "Ciśnienie"))
        self.radioSpeed.setText(_translate("WeatherApp", "Prędkość wiatru"))
        self.radioHuminity.setText(_translate("WeatherApp", "Wilgotność"))
        self.zoomButton.setText(_translate("WeatherApp", "Powiększ"))
        self.menuMenu.setTitle(_translate("WeatherApp", "Menu"))
        self.menuWy_wietl_historyczne_dane.setTitle(_translate("WeatherApp", "Wyświetl historyczą temperaturę"))
        self.menuWsp_rz_dne_2.setTitle(_translate("WeatherApp", "Współrzędne"))
        self.actionMinumum.setText(_translate("WeatherApp", "Minumum"))
        self.actionMaksimum.setText(_translate("WeatherApp", "Maksimum"))
        self.actionSrednia.setText(_translate("WeatherApp", "Średnia"))
        self.action35_88.setText(_translate("WeatherApp", "35.88"))
        self.action36.setText(_translate("WeatherApp", "76.51"))
        self.Xcoord.setText(_translate("WeatherApp", "X:35.88"))
        self.Ycoord.setText(_translate("WeatherApp", "Y:76.51"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WeatherApp = QtWidgets.QMainWindow()
    ui = Ui_WeatherApp()
    ui.setupUi(WeatherApp)
    WeatherApp.show()
    sys.exit(app.exec_())
